//! Execution Engine Type Definitions

use crate::agentic::app_builder_context::AppBuilderExecutionContext;
use crate::agentic::core::{Message, SessionDomain};
use crate::agentic::events::SessionSurfaceMode;
use crate::agentic::product_app_context::ProductAppExecutionContext;
use crate::agentic::round_preempt::DialogRoundPreemptSource;
use crate::agentic::tools::pipeline::SubagentParentInfo;
use crate::agentic::tools::ToolRuntimeRestrictions;
use crate::agentic::workspace::WorkspaceServices;
use crate::agentic::WorkspaceBinding;
use crate::runtime::{AgenticHandles, WorkspaceMount};
use serde_json::Value;
use std::collections::HashMap;
use std::sync::Arc;
use tokio_util::sync::CancellationToken;

/// Controls whether user/global "skip confirmation" preferences may bypass
/// confirmation for tools that declare elevated permissions.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum ToolConfirmationPolicy {
    /// Respect the normal global and per-turn skip-confirmation preferences.
    #[default]
    UserConfigurable,
    /// Permissioned tools must enter the ToolPipeline confirmation lifecycle.
    EnforceForPermissionedTools,
}

/// Execution context
#[derive(Clone)]
pub struct ExecutionContext {
    pub session_id: String,
    pub session_domain: SessionDomain,
    pub dialog_turn_id: String,
    pub turn_index: usize,
    pub agent_type: String,
    pub surface_mode: SessionSurfaceMode,
    pub workspace: Option<WorkspaceBinding>,
    pub context: HashMap<String, String>,
    pub tool_allowlist_override: Option<Vec<String>>,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub skip_tool_confirmation: bool,
    pub tool_confirmation_policy: ToolConfirmationPolicy,
    pub runtime_tool_restrictions: ToolRuntimeRestrictions,
    /// Trusted durable Product App Work binding for this turn.
    pub product_app: Option<ProductAppExecutionContext>,
    pub app_builder: Option<AppBuilderExecutionContext>,
    /// Workspace I/O services (filesystem + shell) injected into tools
    pub workspace_services: Option<WorkspaceServices>,
    /// Per-workspace mount bundle (snapshot manager + agent registry overlay).
    pub workspace_mount: Option<WorkspaceMount>,
    /// Process-wide agentic stack handles (coordinator, scheduler, cron, host).
    pub agentic: Option<AgenticHandles>,
    /// When set, engine may end the turn after a full model round if a user message was queued.
    pub round_preempt: Option<Arc<dyn DialogRoundPreemptSource>>,
}

/// Round context
#[derive(Debug, Clone)]
pub struct RoundContext {
    pub session_id: String,
    pub session_domain: SessionDomain,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub dialog_turn_id: String,
    pub round_id: String,
    pub turn_index: usize,
    pub round_number: usize,
    pub workspace: Option<WorkspaceBinding>,
    pub surface_mode: SessionSurfaceMode,
    pub messages: Vec<Message>,
    pub available_tools: Vec<String>,
    pub model_name: String,
    pub agent_type: String,
    pub context_vars: HashMap<String, String>,
    pub tool_confirmation_policy: ToolConfirmationPolicy,
    pub runtime_tool_restrictions: ToolRuntimeRestrictions,
    pub app_builder: Option<AppBuilderExecutionContext>,
    pub cancellation_token: CancellationToken,
    pub workspace_services: Option<WorkspaceServices>,
    pub workspace_mount: Option<WorkspaceMount>,
    pub agentic: Option<AgenticHandles>,
}

/// Round result
#[derive(Debug, Clone)]
pub struct RoundResult {
    pub assistant_message: Message,
    pub tool_calls: Vec<crate::agentic::core::ToolCall>,
    pub tool_result_messages: Vec<Message>,
    pub has_more_rounds: bool,
    pub finish_reason: FinishReason,
    /// Token usage statistics (from model response)
    pub usage: Option<crate::util::types::ai::GeminiUsage>,
    /// Provider-specific metadata returned by the model.
    pub provider_metadata: Option<Value>,
}

/// Finish reason
#[derive(Debug, Clone, PartialEq)]
pub enum FinishReason {
    /// Normal completion
    Complete,
    /// Need to execute tools
    ToolCalls,
    /// Reached maximum rounds
    MaxRounds,
    /// User cancelled
    Cancelled,
    /// Error
    Error,
}

/// Execution result
#[derive(Debug, Clone)]
pub struct ExecutionResult {
    /// Last assistant message
    pub final_message: Message,
    pub total_rounds: usize,
    pub success: bool,
    /// All new messages generated by this execution (including AI responses and tool results)
    pub new_messages: Vec<Message>,
}
