import { lazy } from 'react';
import { defineCustomSettingsTab } from '../customSettingsRegistration';

export default defineCustomSettingsTab({
  id: 'editor',
  categoryId: 'productApps',
  categoryOrder: 300,
  order: 200,
  aliases: ['code editor', 'font', 'minimap', 'word wrap', 'line number', 'format'],
  claimedSettingNamespaces: [
    'core.editor.font_size',
    'core.editor.font_family',
    'core.editor.line_height',
    'core.editor.tab_size',
    'core.editor.insert_spaces',
    'core.editor.word_wrap',
    'core.editor.line_numbers',
    'core.editor.minimap.enabled',
    'core.editor.minimap.side',
    'core.editor.minimap.size',
    'core.editor.theme',
    'core.editor.auto_save',
    'core.editor.auto_save_delay',
    'core.editor.format_on_save',
    'core.editor.format_on_paste',
    'core.editor.trim_auto_whitespace',
  ],
  draftSettingIds: [
    'core.editor.font_size',
    'core.editor.font_family',
    'core.editor.line_height',
    'core.editor.tab_size',
    'core.editor.insert_spaces',
    'core.editor.word_wrap',
    'core.editor.line_numbers',
    'core.editor.minimap.enabled',
    'core.editor.minimap.side',
    'core.editor.minimap.size',
    'core.editor.theme',
    'core.editor.auto_save',
    'core.editor.auto_save_delay',
    'core.editor.format_on_save',
    'core.editor.format_on_paste',
    'core.editor.trim_auto_whitespace',
  ],
  actions: [
    {
      id: 'editor.reset',
      labelKey: 'settings/editor:actions.reset',
      aliases: ['default editor settings', 'reset code editor'],
    },
  ],
  component: lazy(() => import('@/infrastructure/config/components/EditorConfig')),
});
