//! Product App and Component package authoring.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};
use serde_json::json;
use tokio::fs;

use crate::infrastructure::PathManager;
use crate::util::errors::{BitFunError, BitFunResult};

use super::catalog::{
    AppCatalogVisibility, AppComponentRef, AppDefinition, AppInstallScope, AppInteractionModel,
    AppSurfaceMode, AppTruthSource, AppWorkMultiplicity, CapabilityRef, ComponentDefinition,
    ComponentKind, ComponentOwnerApp, ComponentPackageSource, ComponentSource, ComponentVisibility,
    PermissionSpec, ProductAppLaunch, ProductAppLaunchKind, ProductAppLaunchScopeRequirement,
    SurfaceRef, WorkObjectKind, WorkObjectScope,
};
use super::permissions::AppPermissionSummary;
use super::resolver::{ProductAppResolveRequest, ProductAppResolver};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateProductAppPackageDraft {
    pub app_id: String,
    pub name: String,
    pub description: String,
    pub goal: String,
    #[serde(default = "default_version")]
    pub version: String,
    #[serde(default = "default_agent_type")]
    pub agent_type: String,
    #[serde(default)]
    pub category: String,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default = "default_surface_mode")]
    pub primary_surface_mode: AppSurfaceMode,
    #[serde(default)]
    pub truth_source: Option<AppTruthSource>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateComponentPackageDraft {
    pub component_id: String,
    pub kind: ComponentKind,
    pub name: String,
    pub description: String,
    #[serde(default = "default_version")]
    pub version: String,
    #[serde(default)]
    pub implementation_ref: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WrittenProductAppPackage {
    pub app_id: String,
    pub version: String,
    pub component_lock_digest: String,
    pub package_dir: PathBuf,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WrittenComponentPackage {
    pub component_id: String,
    pub kind: ComponentKind,
    pub version: String,
    pub package_dir: PathBuf,
}

pub async fn create_product_app_package(
    path_manager: &PathManager,
    draft: CreateProductAppPackageDraft,
) -> BitFunResult<WrittenProductAppPackage> {
    validate_package_id("appId", &draft.app_id)?;
    validate_required("name", &draft.name)?;
    validate_required("goal", &draft.goal)?;
    validate_required("version", &draft.version)?;

    let package_dir = path_manager.system_product_app_version_dir(&draft.app_id, &draft.version);
    ensure_new_package_dir(&package_dir).await?;

    let surface_id = format!("{}-surface", draft.app_id);
    let agent_id = format!("{}-agent", draft.app_id);
    let owner = ComponentOwnerApp {
        app_id: draft.app_id.clone(),
        app_version: draft.version.clone(),
    };

    let work_object = WorkObjectKind {
        id: "primary-work".to_string(),
        label: "Primary Work".to_string(),
        scope: WorkObjectScope::Workspace,
        identity_schema: json!({
            "type": "object",
            "required": ["workId"],
            "properties": {
                "workId": { "type": "string" }
            }
        }),
        context_schema: json!({
            "type": "object",
            "properties": {
                "goal": { "type": "string" },
                "workspacePath": { "type": "string" }
            }
        }),
    };

    let surface_component = ComponentDefinition {
        id: surface_id.clone(),
        version: None,
        kind: ComponentKind::Surface,
        name: format!("{} Surface", draft.name),
        description: "Primary Product App surface generated by App Studio.".to_string(),
        package_source: ComponentPackageSource::AppPrivate,
        owner_app: Some(owner.clone()),
        capabilities: vec![
            CapabilityRef {
                id: "context.publish".to_string(),
                title: "Publish structured work context".to_string(),
                description: "Publishes Work-owned context for AI collaboration.".to_string(),
                actions: vec!["context.publish".to_string()],
            },
            CapabilityRef {
                id: "selection.describe".to_string(),
                title: "Describe selection".to_string(),
                description:
                    "Describes the current object or selection without owning durable state."
                        .to_string(),
                actions: vec!["selection.describe".to_string()],
            },
        ],
        permissions: Vec::new(),
        used_by_apps: vec![draft.app_id.clone()],
        visibility: ComponentVisibility::AppDependency,
        dependencies: Vec::new(),
        implementation_ref: Some(format!(
            "app://{}@{}/surfaces/{}",
            draft.app_id, draft.version, surface_id
        )),
    };

    let agent_component = ComponentDefinition {
        id: agent_id.clone(),
        version: None,
        kind: ComponentKind::Agent,
        name: format!("{} Agent", draft.name),
        description: "Agent component generated by App Studio.".to_string(),
        package_source: ComponentPackageSource::AppPrivate,
        owner_app: Some(owner),
        capabilities: vec![CapabilityRef {
            id: "agent.run".to_string(),
            title: "Run agent session".to_string(),
            description: "Starts the configured agent for this Product App.".to_string(),
            actions: vec!["agent.session.start".to_string()],
        }],
        permissions: vec![PermissionSpec {
            kind: "ai".to_string(),
            summary: "Uses the configured AI agent.".to_string(),
            scopes: vec![draft.agent_type.clone()],
        }],
        used_by_apps: vec![draft.app_id.clone()],
        visibility: ComponentVisibility::AppDependency,
        dependencies: Vec::new(),
        implementation_ref: Some(format!("agent://{}", draft.agent_type)),
    };

    let launch = if draft.primary_surface_mode == AppSurfaceMode::ChatPrimary {
        ProductAppLaunch {
            kind: ProductAppLaunchKind::AgentSession,
            target_id: draft.agent_type.clone(),
            scope_requirement: ProductAppLaunchScopeRequirement::WorkspaceOptional,
            agent_type: Some(draft.agent_type.clone()),
            surface_id: Some("primary".to_string()),
        }
    } else {
        ProductAppLaunch {
            kind: ProductAppLaunchKind::ApplicationSurface,
            target_id: draft.app_id.clone(),
            scope_requirement: ProductAppLaunchScopeRequirement::WorkspaceRequired,
            agent_type: None,
            surface_id: Some("primary".to_string()),
        }
    };

    let mut app = AppDefinition {
        id: draft.app_id.clone(),
        version: draft.version.clone(),
        name: draft.name.clone(),
        description: draft.description.clone(),
        goal: draft.goal.clone(),
        interaction_model: if draft.primary_surface_mode == AppSurfaceMode::ChatPrimary {
            AppInteractionModel::Conversation
        } else {
            AppInteractionModel::InteractiveWorkspace
        },
        work_multiplicity: AppWorkMultiplicity::Multiple,
        work_object_kinds: vec![work_object.clone()],
        truth_source: draft.truth_source,
        primary_surface: SurfaceRef {
            component_id: surface_id.clone(),
            surface_id: Some("primary".to_string()),
        },
        primary_surface_mode: draft.primary_surface_mode,
        components: vec![
            AppComponentRef {
                component_id: surface_id,
                kind: ComponentKind::Surface,
                source: ComponentSource::Private,
                role: "primarySurface".to_string(),
                version: None,
                capabilities: Vec::new(),
            },
            AppComponentRef {
                component_id: agent_id,
                kind: ComponentKind::Agent,
                source: ComponentSource::Private,
                role: "agent".to_string(),
                version: None,
                capabilities: Vec::new(),
            },
        ],
        component_lock_id: String::new(),
        permissions: AppPermissionSummary {
            ai: true,
            ..AppPermissionSummary::default()
        },
        install_scope: AppInstallScope::System,
        catalog_visibility: AppCatalogVisibility::InstalledOnly,
        enabled: true,
        icon: "app".to_string(),
        category: draft.category,
        tags: draft.tags,
        launch: Some(launch),
    };

    let resolved = ProductAppResolver::resolve_install(ProductAppResolveRequest {
        app: app.clone(),
        private_components: vec![surface_component.clone(), agent_component.clone()],
        shared_components: Vec::new(),
    })?;
    app.component_lock_id = resolved.app.component_lock_id.clone();

    fs::create_dir_all(&package_dir).await?;
    write_json(package_dir.join("app.json"), &app).await?;
    write_json(
        package_dir.join("work-objects").join("primary-work.json"),
        &work_object,
    )
    .await?;
    write_json(
        package_dir
            .join("components")
            .join(ComponentKind::Surface.path_segment())
            .join(&surface_component.id)
            .join("component.json"),
        &surface_component,
    )
    .await?;
    write_json(
        package_dir
            .join("components")
            .join(ComponentKind::Agent.path_segment())
            .join(&agent_component.id)
            .join("component.json"),
        &agent_component,
    )
    .await?;
    write_text(
        package_dir.join("tests").join("validation-plan.md"),
        "# Validation Plan\n\n- Verify app.json resolves with private components.\n- Verify Work creation records app version and component lock digest.\n- Verify permissions match component requirements.\n",
    )
    .await?;
    ProductAppResolver::write_lock(&package_dir, &resolved.lock).await?;

    Ok(WrittenProductAppPackage {
        app_id: app.id,
        version: app.version,
        component_lock_digest: resolved.lock.digest(),
        package_dir,
    })
}

pub async fn create_component_package(
    path_manager: &PathManager,
    draft: CreateComponentPackageDraft,
) -> BitFunResult<WrittenComponentPackage> {
    validate_package_id("componentId", &draft.component_id)?;
    validate_required("name", &draft.name)?;
    validate_required("description", &draft.description)?;
    validate_required("version", &draft.version)?;

    let package_dir = path_manager.system_component_version_dir(
        draft.kind.path_segment(),
        &draft.component_id,
        &draft.version,
    );
    ensure_new_package_dir(&package_dir).await?;

    let component = ComponentDefinition {
        id: draft.component_id.clone(),
        version: Some(draft.version.clone()),
        kind: draft.kind,
        name: draft.name,
        description: draft.description,
        package_source: ComponentPackageSource::Shared,
        owner_app: None,
        capabilities: vec![CapabilityRef {
            id: "component.contract".to_string(),
            title: "Component contract".to_string(),
            description: "Generated Component Studio contract placeholder.".to_string(),
            actions: vec!["component.validate".to_string()],
        }],
        permissions: Vec::new(),
        used_by_apps: Vec::new(),
        visibility: ComponentVisibility::Developer,
        dependencies: Vec::new(),
        implementation_ref: draft.implementation_ref,
    };

    fs::create_dir_all(&package_dir).await?;
    write_json(package_dir.join("component.json"), &component).await?;
    write_text(
        package_dir.join("src").join("README.md"),
        "# Implementation\n\nPlace the component implementation here.\n",
    )
    .await?;
    write_text(
        package_dir.join("tests").join("contract.md"),
        "# Contract Tests\n\n- Validate component.json.\n- Verify declared capabilities and permissions.\n- Verify Product App references use semver ranges.\n",
    )
    .await?;
    ProductAppResolver::read_component_package(&package_dir).await?;

    Ok(WrittenComponentPackage {
        component_id: component.id,
        kind: component.kind,
        version: draft.version,
        package_dir,
    })
}

async fn write_json(path: PathBuf, value: &impl Serialize) -> BitFunResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).await?;
    }
    let bytes = serde_json::to_vec_pretty(value)?;
    fs::write(&path, bytes).await?;
    Ok(())
}

async fn write_text(path: PathBuf, value: &str) -> BitFunResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).await?;
    }
    fs::write(&path, value).await?;
    Ok(())
}

async fn ensure_new_package_dir(path: &PathBuf) -> BitFunResult<()> {
    if fs::try_exists(path).await? {
        return Err(BitFunError::validation(format!(
            "package already exists: {}",
            path.display()
        )));
    }
    Ok(())
}

fn validate_required(field: &str, value: &str) -> BitFunResult<()> {
    if value.trim().is_empty() {
        return Err(BitFunError::validation(format!("{field} is required")));
    }
    Ok(())
}

fn validate_package_id(field: &str, value: &str) -> BitFunResult<()> {
    validate_required(field, value)?;
    let valid = value
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || ch == '-' || ch == '_');
    if !valid {
        return Err(BitFunError::validation(format!(
            "{field} must contain only ASCII letters, numbers, '-' or '_'"
        )));
    }
    Ok(())
}

fn default_version() -> String {
    "1.0.0".to_string()
}

fn default_agent_type() -> String {
    "agentic".to_string()
}

fn default_surface_mode() -> AppSurfaceMode {
    AppSurfaceMode::ChatPrimary
}

#[cfg(test)]
mod tests {
    use std::time::{SystemTime, UNIX_EPOCH};

    use crate::infrastructure::PathManager;

    use super::*;

    #[tokio::test]
    async fn creates_resolved_product_app_package_with_lock() {
        let root = test_root("product-app");
        let path_manager = PathManager::with_user_root_for_tests(root);
        let written = create_product_app_package(
            &path_manager,
            CreateProductAppPackageDraft {
                app_id: "sample-app".to_string(),
                name: "Sample App".to_string(),
                description: "Sample description".to_string(),
                goal: "Complete sample work".to_string(),
                version: "1.0.0".to_string(),
                agent_type: "agentic".to_string(),
                category: "testing".to_string(),
                tags: vec!["sample".to_string()],
                primary_surface_mode: AppSurfaceMode::ChatPrimary,
                truth_source: None,
            },
        )
        .await
        .unwrap();

        assert!(written.package_dir.join("app.json").exists());
        assert!(written.package_dir.join("app.lock.json").exists());
        assert!(
            written
                .package_dir
                .join("components")
                .join("surfaces")
                .join("sample-app-surface")
                .join("component.json")
                .exists()
        );
    }

    #[tokio::test]
    async fn sidecar_product_app_launches_application_surface() {
        let root = test_root("product-app-sidecar");
        let path_manager = PathManager::with_user_root_for_tests(root);
        let written = create_product_app_package(
            &path_manager,
            CreateProductAppPackageDraft {
                app_id: "sample-sidecar-app".to_string(),
                name: "Sample Sidecar App".to_string(),
                description: "Sample sidecar description".to_string(),
                goal: "Complete sidecar work".to_string(),
                version: "1.0.0".to_string(),
                agent_type: "agentic".to_string(),
                category: "testing".to_string(),
                tags: vec!["sample".to_string()],
                primary_surface_mode: AppSurfaceMode::SidecarLinked,
                truth_source: None,
            },
        )
        .await
        .unwrap();

        let package = ProductAppResolver::read_product_app_package(&written.package_dir)
            .await
            .unwrap();
        let launch = package.app.launch.unwrap();
        assert_eq!(launch.kind, ProductAppLaunchKind::ApplicationSurface);
        assert_eq!(launch.target_id, "sample-sidecar-app");
        assert_eq!(
            launch.scope_requirement,
            ProductAppLaunchScopeRequirement::WorkspaceRequired
        );
        assert_eq!(launch.surface_id.as_deref(), Some("primary"));
        assert!(launch.agent_type.is_none());
    }

    #[tokio::test]
    async fn creates_valid_shared_component_package() {
        let root = test_root("component");
        let path_manager = PathManager::with_user_root_for_tests(root);
        let written = create_component_package(
            &path_manager,
            CreateComponentPackageDraft {
                component_id: "sample-skill".to_string(),
                kind: ComponentKind::Skill,
                name: "Sample Skill".to_string(),
                description: "Sample component".to_string(),
                version: "1.0.0".to_string(),
                implementation_ref: Some("skill://sample".to_string()),
            },
        )
        .await
        .unwrap();

        assert!(written.package_dir.join("component.json").exists());
    }

    fn test_root(name: &str) -> std::path::PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("sparo-authoring-{name}-{nanos}"))
    }
}
